spring:
  application:
    name: user-auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password#123
    driver-class-name: org.postgresql.Driver    